name: PullRequestテンプレ
description: PullRequestのテンプレート
title: ""
assignees:
  - octocat
body:
  - type: textarea
    id: issueNo
    attributes:
      label: Issueへのリンク
      description: 必要に応じてClosingKeyWordを使ってIssueを閉じてください
    validations:
      required: true
 - type: textarea
    id: whatdo
    attributes:
      label: 何をしたか
      description: このプルリクエストで何をしたのか詳細に書いてください
    validations:
      required: true
  - type: textarea
    id: images
    attributes:
      label: 必要ならばスクショ等を貼ってください
      description: UI設計なら必須。コードのリファクタリング等なら無しでOK
    validations:
        required: false
  - type: textarea
    id: questions
    attributes:
      label: 課題等
      description: わからない事や課題があれば書いてください
    validations:
        required: false
  - type: textarea
    id: remarks
    attributes:
      label: 備考欄
      description: 補足情報やその他の情報を書いてください
    validations:
        required: false