name: namae_dogs
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  go_router: 6.5.8
  hooks_riverpod: ^2.3.6
  riverpod_annotation: 2.1.1
  freezed_annotation: 2.2.0
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: 2.2.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: 2.3.2
  flutter_lints: 2.0.1
  mocktail: 0.3.0
  riverpod_generator: ^2.2.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: true
  ios: true